### ISSUE TITLE
Failure to Load, plugin wont work

### ISSUE THREAD

**Issue by goober9763** [IHasName/CustomHeads#1]
No plugin Files are being created, I get this error:
[Server] ERROR Could not load 'plugins/CustomHeads.jar' in folder 'plugins': uses the space-character (0x20) in its name

**Comment by IHasName** [comment]
Wich Spigot version are you using?

EDIT: Also please provide the Full Stacktrace

**Comment by IHasName** [comment]
Closing Issue

Not recreatable
