### ISSUE TITLE
Disabling update notifications does nothing

### ISSUE THREAD

**Issue by Matocolotoe** [IHasName/CustomHeads#13]
You still get notified that a new version is available if you set `updateNotify` to false

**Comment by IHasName** [comment]
Hi Matocolotoe,
have you reloaded the Plugin after changing it?

EDIT: Also which Notification are we talking about? Ingame or Server Console? If you're talking about the Notification in Console then it can't be disabled by default.

**Comment by Matocolotoe** [comment]
i'm talking about console notification so it should be normal though you can add an config option for that i might do a pull request soon to add it ^^

**Comment by IHasName** [comment]
Updated it in the newest Release
