### ISSUE TITLE
Permission for getting own head

### ISSUE THREAD

**Issue by John-H-Smith** [IHasName/CustomHeads#16]
Hi, is there a permission to disable players getting their own head?

Thanks in advance.

**Comment by IHasName** [comment]
Do you mean the Command or in the Menu itself?

In case of the Command its heads.use.more.get
If its about the Menu then theres no Permission set currently. But you can remove the Heads via the settings.json File which is located in your Language Folder.

If you have any other Questions feel free to join my [Discord](https://discord.gg/wc5AzEm)

**Comment by IHasName** [comment]
Any other Questions left or is everything resolved?

**Comment by John-H-Smith** [comment]
No thats it, thanks!
