### ISSUE TITLE
Option "No" with red square as a head does not work when heads are buyable

### ISSUE THREAD

**Issue by KrepelkaCZ** [IHasName/CustomHeads#18]
Dear StoneGamer,

you can take out of the GUI the red square as a head if you want to decline head payment when head is buyable.

Steps to reproduce:
1.  head is buyable
2.  buy the head
3.  when there is green and red squares as a decision to pick yes and no pick No -> you take the square out of the GUI

**Comment by IHasName** [comment]
Which Spigot Version are you using?

**Comment by KrepelkaCZ** [comment]
I am using:
![image](https://user-images.githubusercontent.com/51677895/78504352-e461a800-776c-11ea-8fcb-c6ad23ab2903.png)

**Comment by IHasName** [comment]
Should be fixed in the newest Release
