### ISSUE TITLE
Please add a /heads give cmd

### ISSUE THREAD

**Issue by jusobreira** [IHasName/CustomHeads#20]
Hi, your plugin it's amazing, but can you add a /heads give <nick> <head> command? It would be awesome!!

**Comment by IHasName** [comment]
What do you mean with /heads give? Like for example /heads give <playername>?
If you mean that you can use /heads get <playername>

**Comment by jusobreira** [comment]
I mean like give other player a head. If i want to run on console or give a regular player a head without drop the head. Something like /heads give IHasName jusobreira and then you recieve my head

**Comment by IHasName** [comment]
Oh okay
I'll update /heads get for that ^^ (Right now you can do "/heads get jusobreira" to get the Head for yourself)

**Comment by jusobreira** [comment]
Amazing! Thanks! I'll review the plugin on spigot :D
