### ISSUE TITLE
command /heads works wierd

### ISSUE THREAD

**Issue by Phant420** [IHasName/CustomHeads#21]
when i had server on 1.15 everything was fine but when i updated to 1.16.1 command /heads does't work as intented. I mean when i type /heads menu opens up but when im choosing category i take the head instead of opening a category

**Comment by IHasName** [comment]
Did you update to the latest CustomHeads Verision? (Should be 3.0.2)

**Comment by IHasName** [comment]
So... is this still an Issue or has it been resolved?

**Comment by gen1n** [comment]
@IHasName I am facing the same issue.
Server: Paper 1.18.2
Plugin: Custom Heads [1.8-1.18]  version: 3.0.5

Warnings:
During server power on, it shows:

[WARNING] .... Legacy plugin CustomHeads v3.0.5 does not specify an api-version.
[INFO] .... [CustomHeads] Warning : Hrm. Seems like CustomHeads wasn't tested on this Minecraft Version (v1_18_R2) yet...
[INFO] .... [CustomHeads] Warning : Feel free to join my Discord to know when it gets updated

So is it only update issue?
This is what i am seeing:
and on clicking heads, it attaches to my cursor.
![image](https://user-images.githubusercontent.com/16335692/157466569-a8a77ce0-095b-4c16-89ae-3d0ccad0d186.png)
