### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by azmmr** [IHasName/CustomHeads#23]
Dear, moderator 
I have an issue with the heads plugin. When i type /heads help it doesn't show anything. 
Please help!

**Comment by IHasName** [comment]
Are there any Errors thrown by the Plugin in the Console?

**Comment by itzme1on** [comment]
maybe try **/cheads**?

**Comment by IHasName** [comment]
Will be closing this due to lack of Information and recreatability
