### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by OneSmallShot** [IHasName/CustomHeads#24]
Hi! Im currently having trouble. When I do the command /heads I can only pick up the heads, not view the categories. I am doing this in 1.16.1, but tried in 1.14 too and had the same issues.
Thank you.

**Comment by itzme1on** [comment]
Good day, **OneSmallShot**!

Could you send me all the details about your server, such as the name of the kernel used and the list of plugins used on the server? Are there any errors in the console?

_I apologize for my knowledge of English, I just live in Russia and do not know all the words, so I use a translator :]_

**Comment by OneSmallShot** [comment]
It's a minehut server with no other plugins installed. I don't believe there are any other errors in the console. And dont worry about your english, you are doing great. 👍

**Comment by itzme1on** [comment]
What is _Minehut_? Server hosting?

**Comment by IHasName** [comment]
Check the Version of the Plugin with /heads info
If it shows 3.0.1 then it wasnt updated by Minehut (@itzme1on Yes Minehut is a Server Hoster)
I can't do anything to fix this because I don't own Minehut

**Comment by OneSmallShot** [comment]
Alright thank you.
