### ISSUE TITLE
Add PlayerClickCustomHeadEvent to API

### ISSUE THREAD

**Issue by Shynixn** [IHasName/CustomHeads#25]
## Issue Description

Hi, I was wondering about if you could add an event called ``PlayerClickCustomHeadEvent`` to the CustomHeads API?
It should be triggered once a custom head has been selected from your GUI which allows other plugins to "use" the
selected head for their personal purposes. 

For example the HeadDatabasePlugin broadcasts this event:

````
@EventHandler
public void onPlayerClickOnHeadEvent(PlayerClickHeadEvent event) {
  Player player = event.getPlayer();
  ItemStack itemStack = event.getHead();
}

````

## Infos
  - Plugin Version:
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2):

**Comment by IHasName** [comment]
Added by latest Version
