### ISSUE TITLE
Gui not working

### ISSUE THREAD

**Issue by Robeanie** [IHasName/CustomHeads#26]
when I do /heads it opens fine but when i click on any of the categories they don't open I just get the head used for the category
![image](https://user-images.githubusercontent.com/70145564/91044404-218be100-e60d-11ea-8cae-873ca5dcbaf9.png)

**Comment by IHasName** [comment]
First off please use the Issue Template
Secondly:
- Whats the Minecraft/Spigot Version?
- Whats the Plugin Version?
