### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by strich3** [IHasName/CustomHeads#28]
## Feature Description

/

**Comment by itzme1on** [comment]
![image](https://user-images.githubusercontent.com/47828778/122467015-49906a80-cfba-11eb-8eff-33c7c6b5724f.png)

**Comment by yannicklamprecht** [comment]
Holy shit it the plugin cursed. The code looks like he stopped updating the plugin 6 years ago.

Such a big technical depth.

**Comment by IHasName** [comment]
> Holy shit it the plugin cursed. The code looks like he stopped updating the plugin 6 years ago.
> 
> Such a big technical depth.

wdym exactly? If you're talking about all the NMS Stuff, yes. Most of the Stuff in this Plugin I either didnt have the time to rewrite anything or didn't want to tbh. Always open for suggestions tho

**Comment by yannicklamprecht** [comment]
> > Holy shit it the plugin cursed. The code looks like he stopped updating the plugin 6 years ago.
> > Such a big technical depth.
> 
> wdym exactly? If you're talking about all the NMS Stuff, yes. Most of the Stuff in this Plugin I either didnt have the time to rewrite anything or didn't want to tbh. Always open for suggestions tho

Yeah mainly. Started migrating stuff locally but lost interest. I've no clue why you implemented yourself a tag system for your ItemStacks. Why is that needed for a "simple" heads plugins?

**Comment by IHasName** [comment]
The Tag Stuff started as a way to know which Item is clicked and whatever. I wanted to rewrite it but didnt have Time or Motivation to do it since it worked.

Also Side Note... Don't look at the first Version of the Plugin. I just started coding in Java and trust me that Code is more cursed than the current

**Comment by itzme1on** [comment]
lol, so write your plugin, smartass

**Comment by IHasName** [comment]
Support added by latest Version
