### ISSUE TITLE
Request: Paying by playerpoints

### ISSUE THREAD

**Issue by jeffry1829** [IHasName/CustomHeads#31]
## Feature Description
It'd be great if this plugin can support paying by playerpoints
(or an api to register new pay methods)

Thanks!

**Comment by IHasName** [comment]
I think Vault already has a way of adding Custom Payment Systems.
But let me know if youi want a simple Addition ^^

**Comment by jeffry1829** [comment]
> I think Vault already has a way of adding Custom Payment Systems.
> But let me know if youi want a simple Addition ^^

I don't see "register payment for plugin" method in vault api.
May I ask how to add custom payment?
Thanks!

**Comment by IHasName** [comment]
Found [this](https://www.spigotmc.org/threads/registering-a-plugin-with-vault.189366/#post-1984960) Thread on Spigot
The Code referenced in that one is [here](https://github.com/MilkBowl/Vault/blob/76d6ab9098a2dc3db676b5fa5acdbe3086818c8f/src/net/milkbowl/vault/Vault.java#L378)
Update 1:
Reference Classes can also be found [here](https://github.com/MilkBowl/Vault/tree/master/src/net/milkbowl/vault/economy/plugins)

**Comment by jeffry1829** [comment]
Sorry if I misunderstood what you mean.
Seems like hook into vault will force every plugins use my custom Economy.
However, what I want is a config in CustomHeads:
economy: "vault" or
economy: "myEconomy"
such that I can register new payment method in CustomHeads api, and use it in config.
Thank you!

**Comment by IHasName** [comment]
oh ok. I'll see what I can do

**Comment by IHasName** [comment]
Added by latest [Version](https://github.com/IHasName/CustomHeads/releases/tag/3.0.4)
