### ISSUE TITLE
either im retarded or adding heads by the texture doesnt work

### ISSUE THREAD

**Issue by jaredthedeveloper** [IHasName/CustomHeads#33]
## Infos
  - Plugin Version:
  - Minecraft Version (ex. Spigot idk, Paper idk): its version 1.17.1 or something

**Comment by itzme1on** [comment]
can you give more info? this is not mod, this is Spigot / Bukkit plugin, we need server core version

**Comment by jaredthedeveloper** [comment]
im using the most recent version, 1.17.1 game version and the most recent spigot buildtools for that version the /heads add command always fails no matter what i do

**Comment by itzme1on** [comment]
When using `/heads add` command, you must hold the player's head in your hand, after which it will be added to collection. `/heads add` command adds to your collection head that you are holding in your hand at the moment.

![2021-11-01_08 05 55](https://user-images.githubusercontent.com/47828778/139628965-90c61c2c-59db-4b68-995c-3b35a8f4116f.png)
![2021-11-01_08 06 09](https://user-images.githubusercontent.com/47828778/139628969-7daba269-befd-49e0-b959-d3873ba22224.png)

**Comment by jaredthedeveloper** [comment]
Oh gotcha, thanks for the help
