### ISSUE TITLE
"Plugin is disabled."

### ISSUE THREAD

**Issue by uhhams** [IHasName/CustomHeads#35]
## Issue Description
whenever I use the /heads command it says that "an internal error has occurred", so I checked the console and this is the error message that pops up: "Cannot execute command 'heads' in plugin CustomHeads v3.0.3 - plugin is disabled." I dont know how to fix this
## Infos
  - Plugin Version: 1.17
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2): Paper 1.18.1

**Comment by IHasName** [comment]
1.18 isn't supported right now
Will be releasing an Update for 1.18 soon
