### ISSUE TITLE
Default Steve head appears in menu

### ISSUE THREAD

**Issue by gen1n** [IHasName/CustomHeads#36]
@IHasName 
Server: Paper 1.18.2
Plugin: Custom Heads [1.8-1.18] version: 3.0.5

_Note: Please allow few days for reply._

Warnings:
During server power on, it shows:

[WARNING] .... Legacy plugin CustomHeads v3.0.5 does not specify an api-version.
[INFO] .... [CustomHeads] Warning : Hrm. Seems like CustomHeads wasn't tested on this Minecraft Version (v1_18_R2) yet...
[INFO] .... [CustomHeads] Warning : Feel free to join my Discord to know when it gets updated

(This is in continuation to [Issue 21](https://github.com/IHasName/CustomHeads/issues/21) . I had posted a reply there but the thread was already closed, I guess thats why I haven't received a reply yet.)
So is it only update issue?
This is what i am seeing:
and on clicking heads, it attaches to my cursor. Also, i can get that steve head in my inventory and place it down on the ground.
![image](https://user-images.githubusercontent.com/16335692/158125351-eacf1fdd-9be1-40c5-9483-ff3e5ba03798.png)

**Comment by IHasName** [comment]
Yes it's just an Update Issue
