### ISSUE TITLE
Invalid Handler passed as Argument

### ISSUE THREAD

**Issue by ChrissW-R1** [IHasName/CustomHeads#38]
## Issue Description
I got an error while enabling the plugin:
`de.likewhat.customheads.economy.errors.InvalidEconomyHandlerException: Invalid Handler passed as Argument`

Looks like there is a problem on using the economy plugin. We using EssentialsX as economy and Vault as the default bridge.

## Infos
  - Plugin Version: 3.0.5
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2): Paper 1.18.2 (build 283)
  - Vault: 1.7.3
  - EssentialsX: 2.19.4

## Logs
https://pastebin.com/9eYHusQs

**Comment by IHasName** [comment]
It's an Issue with Essentials loading after CustomHeads
Will be fixed with the next Update
