### ISSUE TITLE
Users unable to join server after install

### ISSUE THREAD

**Issue by jetcoil** [IHasName/CustomHeads#39]
After dropping in this plugin, I was able to join my server without issue using both my Java and my Bedrock account. Two other Java players tried to join but were kicked immediately, and repeatedly. They share the same permissions as my Bedrock account (member of server, as opposed to Mod or higher rank). 

This is the startup log of the plugin being implemented and a player, username xXVampzTheBatXx, being kicked several times:
https://pastebin.com/xMM2pKgN

After I deleted the .jar and its files and restarted the server, all players were able to join without issue.

**Spigot 1.18.1**

Kicked user reported receiving this error:
![Screenshot_2022-04-16_105330](https://user-images.githubusercontent.com/99770268/163742665-b704e17a-04d0-490a-8e7c-489014011dfb.png)

**Comment by IHasName** [comment]
The Player you mentioned seems to timeout... The Plugin only checks for Updates for Users that have Op or the right Permission when they join so I'm not sure what would cause this Issue.
I tried using Geyser and Spigot with 1.18.1 and it worked fine so far...
What Minecraft Version was the Player using when trying to join?

**Comment by GavinGoGaming** [comment]
> ... What Minecraft Version was the Player using when trying to join?

from the image, it seems like Minecraft 1.18.2 client while 1.18.1 server/plugin. Could be using ViaVer or Multicon tho
