### ISSUE TITLE
own head

### ISSUE THREAD

**Issue by TitianH** [IHasName/CustomHeads#4]
hey, if you want to get your own head, you always see the head of the first player who used /heads since server start

**Comment by IHasName** [comment]
What Spigot Version are you using?

**Comment by TitianH** [comment]
PaperSpigot version git-Paper-1384 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Did not test with normal Spigot

**Comment by TitianH** [comment]
seems to be fixed in the latest version, thx :)
