### ISSUE TITLE
Add permission to ignore price

### ISSUE THREAD

**Issue by Luky584** [IHasName/CustomHeads#42]
## Feature Description
Hello,
would it be please possible to add permission e.g. **heads.free**, to make heads free/unlocked for some people?

Example usages:
- Staff could have free heads, regular players should pay.
- Creative world - free heads; Survival world - players will pay.

Thanks much!

**Comment by IHasName** [comment]
There actually is a Permission for that (heads.unlockAllHeads.<category>)
I forgot to add it to the Wiki so I updated it
