### ISSUE TITLE
Permission not working

### ISSUE THREAD

**Issue by MrLaikz18** [IHasName/CustomHeads#43]
## Issue Description
When a player (with permission "heads.*") disconnect, when he reconnect, he doesn't have access to head's categories.
I tried with all subperms and all menu's perms, and still not working.
Thanks

## Infos
  - Plugin Version:
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2):

**Comment by IHasName** [comment]
What Permission Plugin are you using?

**Comment by MrLaikz18** [comment]
LuckPerms, I tried permission on parent and directly player, still not working

**Comment by Vitromara** [comment]
Same for me. In luckperms i have a group with this permission "heads.viewCategory.* and "heads.use" inherited from the default group. After the user has reconnected he see all category "locked".
Please, how can fix this issue?

PaperMC 1.20
Custom heads 3.0.9

**Comment by IHasName** [comment]
Fixed with latest release
