### ISSUE TITLE
Alphabet heads not working

### ISSUE THREAD

**Issue by eightballz** [IHasName/CustomHeads#44]
## Issue Description
Whenever I place down a head with a letter on it twice (such as two Gs), the head turns black or into part of a sign texture.

## Info
  - Plugin Version: 3.0.7
  - Minecraft Version: Paper 1.19.3

https://user-images.githubusercontent.com/75538010/218592180-64c1d312-ecd7-49b9-861b-01e6bcad7453.mp4

**Comment by itzme1on** [comment]
What plugins do you use? I also use CustomHeads on my Paper 1.19.3 server, but I don't see such a problem

**Comment by IHasName** [comment]
Is this still an Issue? @Lucky0888
