### ISSUE TITLE
UTF-8 ?

### ISSUE THREAD

**Issue by Matocolotoe** [IHasName/CustomHeads#9]
When I put special characters into the .json files they are replaced by some weird "??"
Could you please support UTF-8 ? Or if it's already supported, how can I insert special characters

**Comment by IHasName** [comment]
Which Special Characters where you trying to use that got replaced?

**Comment by Matocolotoe** [comment]
For instance : é, ê, è, ...
(I am french)

**Comment by Matocolotoe** [comment]
Anything new ? @MrSteinMC

**Comment by IHasName** [comment]
Not yet... sorry bout that but School got pretty intese last month =/

**Comment by Matocolotoe** [comment]
Any news ?

**Comment by Matocolotoe** [comment]
@MrSteinMC what thing is actually getting text from the JSON files (or/and parsing it ?) because I couldn't find out where the problem is throughout the code, even the pom.xml specifies "UTF-8"

**Comment by Matocolotoe** [comment]
Found a way to fix this with https://www.freeformatter.com/json-escape.html#ad-output

**Comment by IHasName** [comment]
Hi @Matocolotoe 
sorry for not replying to this but I figured out why it happened.

**Comment by Matocolotoe** [comment]
what did you found ?
